"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");
require("../js/omnidexer.js");
Object.assign(global, require("../js/utils-ui.js"));
const PageFilterSpells = require("../js/filter-spells.js");
const root = path.join(__dirname, "..");
const clone = value => JSON.parse(JSON.stringify(value));
async function main () {
 DataUtil.loadJSON = async url => JSON.parse(fs.readFileSync(path.join(root, url), "utf8"));
 const raw = await DataUtil.spell.pLoadRaw();
 const snapshot = JSON.stringify(raw);
 const loaded = await DataUtil.spell.pLoadAll();
 assert.strictEqual(loaded.length, raw.length);
 const get = (name, source = "PHB") => loaded.find(sp => sp.name === name && sp.source === source);
 const pf = Object.create(PageFilterSpells.prototype);
 global.$ = html => html;
 const RenderSpells = vm.runInThisContext(`${fs.readFileSync(path.join(root, "js/render-spells.js"), "utf8")}\nRenderSpells;`);
 const lookup = await RenderSpells.pGetSubclassLookup();
 const historical = {class: {name: "Artificer", source: "ERLW"}, subclass: {name: "Alchemist", source: "ERLW"}};
 const historicalLink = Parser._spSubclassItem(historical, false, lookup);
 assert(historicalLink.includes("artificer_tce") && historicalLink.includes("Available printing"));
 assert.strictEqual(historical.class.source, "ERLW");
 const duergarLink = DataUtil.spell.getRaceAssociationLink({name: "Dwarf (Duergar)", source: "SCAG"});
 assert.strictEqual(duergarLink.source, "MTF");
 for (let i = 0; i < raw.length; i++) {
  const source = raw[i], spell = loaded[i];
  assert(!source.classes.fromSubclass && !source.races && !source.backgrounds, `${source.name} has duplicated owner associations`);
  assert.deepStrictEqual(spell.classes.fromClassList, source.classes.fromClassList);
  assert.deepStrictEqual(spell.classes.fromClassListVariant, source.classes.fromClassListVariant);
  const before = clone({classes: spell.classes, races: spell.races, backgrounds: spell.backgrounds});
  pf.mutateForFilters(spell);
  RenderSpells.$getRenderedSpell(spell, lookup);
  assert.deepStrictEqual(clone({classes: spell.classes, races: spell.races, backgrounds: spell.backgrounds}), before);
 }
 assert.strictEqual(JSON.stringify(raw), snapshot, "Loading, filtering, and rendering must not mutate source spells");
 const dispel = get("Dispel Magic");
 const dispelHash = UrlUtil.URL_TO_HASH_BUILDER[UrlUtil.PG_SPELLS](dispel);
 const editorCopy = await Renderer.hover.pCacheAndGet(UrlUtil.PG_SPELLS, "PHB", dispelHash, {isRaw: true});
 const hoverCopy = await Renderer.hover.pCacheAndGet(UrlUtil.PG_SPELLS, "PHB", dispelHash);
 assert(!editorCopy.classes.fromSubclass && !editorCopy.races && !editorCopy.backgrounds);
 assert(hoverCopy.classes.fromSubclass.length > 0);
 assert.notStrictEqual(editorCopy, hoverCopy);
 for (const name of ["Payaso", "Planeswalker"]) assert(dispel.classes.fromClassList.some(c => c.name === name));
 assert(get("Encode Thoughts", "GGR").backgrounds.some(b => b.name === "Dimir Operative"));
 assert(get("Mind Sliver", "TCE").races.some(r => r.name === "Kobold" && r.source === "MPMM" && !r.isUnavailable));
 for (const [name, background] of [["Borrowed Knowledge", "Lorehold Student"], ["Kinetic Jaunt", "Prismari Student"], ["Silvery Barbs", "Silverquill Student"], ["Vortex Warp", "Quandrix Student"], ["Wither and Bloom", "Witherbloom Student"]]) assert(get(name, "SCC").backgrounds.some(b => b.name === background));
 const sample = clone(raw.find(s => s.name === "Dispel Magic" && s.source === "PHB"));
 const owners = {class: [{name:"Fighter",source:"PHB",subclasses:[{name:"Test",source:"TEST",additionalSpells:[{prepared:{3:["dispel magic|phb"]}}]}]}], race:[{name:"Test Race",source:"TEST",additionalSpells:[{innate:{5:{daily:{1:["dispel magic|PHB"]}}}}]}], background:[{name:"Test Background",source:"TEST",additionalSpells:[{expanded:{s3:["dispel magic|PHB"]}}]}]};
 const beforeOwners = JSON.stringify(owners);
 const index = DataUtil.spell.getAssociationIndex(owners, raw);
 const enriched = DataUtil.spell.getCopyWithAssociations(sample, index);
 assert(enriched.classes.fromSubclass.some(sc => sc.subclass.name === "Test"));
 assert(enriched.races.some(r => r.name === "Test Race"));
 assert(enriched.backgrounds.some(b => b.name === "Test Background"));
 assert.deepStrictEqual(enriched.classes.fromClassList, sample.classes.fromClassList);
 assert.strictEqual(JSON.stringify(owners), beforeOwners, "Compiler must not alter grant modes or conditions");
 owners.class[0].subclasses[0].additionalSpells = []; owners.race[0].additionalSpells = []; owners.background[0].additionalSpells = [];
 assert.deepStrictEqual(DataUtil.spell.getCopyWithAssociations(sample, DataUtil.spell.getAssociationIndex(owners, raw)).classes, sample.classes);
 const visitor = {class:[{name:"Visitor",source:"TEST",classSpells:["dispel magic|PHB",{class:"Wizard",source:"PHB"},{filter:{schools:["A"],levels:[3]}}],subclasses:[{name:"Visitor Subclass",source:"TEST",subclassSpells:["dispel magic|PHB"],subSubclassSpells:{Specialization:["dispel magic|PHB"]}}]}]};
 const personal = DataUtil.spell.getCopyWithAssociations(sample, DataUtil.spell.getAssociationIndex(visitor, raw, {isHomebrew:true}));
 assert.strictEqual(personal.classes.fromClassList.filter(c => c.name === "Visitor").length, 1);
 assert(personal.classes.fromSubclass.some(s => s.subclass.subSubclass === "Specialization"));
 assert.deepStrictEqual(DataUtil.spell.getCopyWithAssociations(sample, DataUtil.spell.getAssociationIndex(visitor, raw)).classes, sample.classes, "Published classes never grant normal class membership");
 const cacheBefore = DataUtil.spell._associationIndex;
 await DataUtil.spell.pInitAssociations(); assert.strictEqual(DataUtil.spell._associationIndex, cacheBefore);
 BrewUtil.homebrew = {background:[{name:"Visitor Background",source:"TEST",additionalSpells:[{expanded:{s3:["dispel magic|PHB"]}}]}]};
 await DataUtil.spell.pInitAssociations();
 assert(DataUtil.spell.getCopyWithAssociations(sample).backgrounds.some(b => b.name === "Visitor Background"));
 BrewUtil.homebrew = {}; await DataUtil.spell.pInitAssociations();
 assert(!(DataUtil.spell.getCopyWithAssociations(sample).backgrounds || []).some(b => b.name === "Visitor Background"));
 const allClasses = await DataUtil.class.loadJSON();
 assert(allClasses.class.every(c => !c.classSpells));
 assert(allClasses.class.every(c => (c.subclasses || []).every(s => !s.subclassSpells && !s.subSubclassSpells)), "Published owners use additionalSpells exclusively");
 const imported = allClasses.class.find(c => c.name === "Artificer (Revisited)");
 assert(imported && imported.classFeatures.length === 20 && imported.subclasses.length === 4);
 assert(imported.subclasses.every(s => s.subclassFeatures.flat().length > 0));
 const importedText = JSON.stringify(imported);
 assert(!/"type":"ref(?:Class|Subclass)Feature"/.test(importedText));
 console.log(`PASS: ${raw.length} spells; owner relations, immutable class lists, grant conditions, cache invalidation, and legacy homebrew.`);
}
main().catch(error => {console.error(error); process.exitCode = 1;});
